<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PelaksanaSeeder extends Seeder
{
    public function run(): void
    {
        $timestamp = now();
        $data = [
            ['1_ALMIRA_SYAMSURI', 'Almira Syamsuri, dr.'],
            ['1_ARIS_MUKTI', 'Aris Mukti, drg.'],
            ['1_DESI FITRI', 'Desi Fitri, dr.'],
            ['1_DIAN_MULIASARI', 'Dian Muliasari, dr.'],
            ['1_DIMAS', 'Dimas Zabirurrohman Putra, dr.'],
            ['1_DITTA_IKA', 'Ditta Ika P, drg.'],
            ['1_FADHILA', 'Fadhila Shofia Ningtyas, drg.'],
            ['1_HARDJANTI', 'Hardjanti, dr.'],
            ['1_HASSITA_WENDA', 'Hassita Wenda M, dr.'],
            ['1_IMAM_MUS', 'Imam Mustaghfirin Ibnussina, dr'],
            ['1_INTERNSHIP', 'Internship, dr.,Magang'],
            ['1_NOVIA', 'Novia, dr.'],
            ['1_NURCHOLIS', 'Nurcholis, dr.'],
            ['1_PRAMONO', 'Pramono, dr.'],
            ['1_SUDJARWANTO', 'Sudjarwanto, dr.'],
            ['1_TEGAR', 'Tegar Alend Renaldhy, dr.'],
            ['1_TOMY_OEKY', 'Tomy Oeky, dr.'],
            ['1_UBAIDILLAH', 'Ubaidillah Romadlon Al Fairuzi, dr'],
            ['1_WILDAN', 'Wildan Firdaus, dr.'],
            ['2_AFIF_MAULANA', 'Afif Maulana Firmansyah, dr.,SpM'],
            ['2_AGUNG', 'Agung,dr.,SpM'],
            ['2_AHADY', 'Ahady. SpJP'],
            ['2_AKHMAD_ZAINUL', 'Akhmad Zainul Arifin, dr.,Sp.N.M.Kes'],
            ['2_ANDRI_RUSLY', 'A. Rusly, dr.Sp.An'],
            ['2_ANDRI_SUBIANTORO', 'Andri Subiantoro,dr.Sp.An'],
            ['2_AULIA_RAD', 'Aulia, dr.,SpRAD'],
            ['2_BAIDLOWI', 'Akhmad Ikhwan Baidlowi, dr,Sp.OG'],
            ['2_BOY_HARIJADI', 'Boy Harijadi, dr.,SpA'],
            ['2_BUDI_PRASETYO', 'Bd. Prasetyo,Sp.An'],
            ['2_CITRA_AHDI', 'Citra Ahdi Prasetya.,Sp.OT'],
            ['2_DARA_DASAWULANSARI', 'Dara Dasawulansari S,dr.Sp.OG'],
            ['2_DAVID', 'David, dr.,SpPD'],
            ['2_EVA_NURYANTI', 'Eva Nuryanti, drg. Sp.KGA'],
            ['2_FAUZIA', 'Fauzia Risma Rahayu, dr.,Sp.N'],
            ['2_FERDIAN', 'Ferdian Rizky Hutomo, drg. Sp.BMM'],
            ['2_FITRA_HARDIAN', 'Fitra Hardian Prisnamurti,dr.Sp.U'],
            ['2_GAGAK_ISMANU', 'G.Ismanu, dr., Sp.BU'],
            ['2_GUSTI', 'Gusti Ramadani, dr.Sp.BTKV'],
            ['2_HAPSARI_PARAMITA', 'Hapsari Paramita N., dr.Sp.P'],
            ['2_IDA_DEWI', 'Ida Dewi, dr.,SpS'],
            ['2_IMAM_BAKHRUDIN', 'Imam Bakhrudin, dr.,SpOT'],
            ['2_IRA_PUSPITA', 'Ira Puspita, dr.,SpKK'],
            ['2_ISTIQOMAH', 'Istiqomah,dr,Sp,PK'],
            ['2_JOKO_SULISTYO', 'Joko Sulistyo, dr.SpAnd'],
            ['2_LUTHFINA', 'Luthfina Mufidati, dr. Sp.JP'],
            ['2_MARGARETHA', 'Margaretha Claudhya F., Sp.OG'],
            ['2_MEI_RIA', 'Mei Ria, dr.,SpKFR'],
            ['2_MENINA_VILANOVA', 'Menina Vilanova Syamsuri,dr,Sp.KJ'],
            ['2_MUTIA_HAPSARI', 'Mutia Hapsari, dr.,SpM'],
            ['2_NAQVI', 'M. Naqvi Al Farisi, dr. Sp.N'],
            ['2_NETIANA', 'Netiana, dr.,SpTHT-KL'],
            ['2_PAUNDRA_HUTAMA', 'Paundra Hutama,dr.Sp.B.'],
            ['2_RETNO_ANAK', 'Retno, dr., SpA'],
            ['2_RETNO_RAD', 'Retno, dr.,SpRAD'],
            ['2_RICARDO', 'Ricardo Adrian N, dr. Sp.JP'],
            ['2_RIDWAN', 'Ridwan, dr.,SpTHT'],
            ['2_RIZKI_DIAH', 'Rizki Diah Anggraeni., dr.Sp.P'],
            ['2_ROCHERMAN', 'Rocherman Gema Adytama, Sp.P'],
            ['2_ROY_DWI', 'Roy Dwi A, dr.,SpU'],
            ['2_STELLA', 'Stella Pravita, dr.Sp.PD'],
            ['2_SUSETYO_ATMOJO', 'Susetyo Atmojo, dr.,SpJP'],
            ['2_SYAHMI_ANAK', 'Syahmi, dr., SpA'],
            ['2_THAYYIB', 'M.Thayyib, dr.,SpPD'],
            ['2_WAHYU_SUGIHARTO', 'Wahyu Sugiarto, dr., Sp.An'],
            ['2_WINDA_RAD', 'Herwinda Octaviana Presti, dr.,SpRAD'],
            ['3_ANA NURLAILI', 'Ana Nurlaili,Apoteker'],
            ['3_ANIS', 'Anis Rokhiatin, A.Md.Keb'],
            ['3_ANIVATIN_LAB', 'Anivatin, Laborat'],
            ['3_ASIH_GIZI', 'Asih, Gizi.'],
            ['3_ASRI_USG', 'Asri, USG'],
            ['3_ASTRID_LAB', 'Astrid, Laborat'],
            ['3_AZHAR', 'Azhar Fathiya'],
            ['3_BHAYANGKARA', 'Bhayangkara RS'],
            ['3_DANI_LAB', 'Dani, Laborat'],
            ['3_DEDDIE_LAB', 'Deddie, Laborat'],
            ['3_DEWI_LAB', 'Dewi, Laborat'],
            ['3_DIYAN_LAB', 'Diyan, Laborat'],
            ['3_DONNY_FISIO', 'Donny R, Fisioterapi'],
            ['3_ELVINA', 'Elvina Triana, Ass.'],
            ['3_EMMY', 'Emmy Rahmawati, A.Md.Keb'],
            ['3_HARTATIK', 'Hartatik, Psi.'],
            ['3_IKA_NURFITA', 'Ika, Ass Mata'],
            ['3_JEMY_LAB', 'Jemy, Laborat'],
            ['3_KALITIDU', 'RSM Kalitidu'],
            ['3_KUSAIRI', 'Kusairi'],
            ['3_LINDA_GIGI', 'Linda A, Gigi.'],
            ['3_LISKA_LAB', 'Liska, Laborat'],
            ['3_LUTHFI', 'Luthfi'],
            ['3_NINIS_FISIO', 'Ninis, Fisioterapi.'],
            ['3_NOVITRI', 'Novitri, Asuhan Farmasi'],
            ['3_PRATIKNO_LAB', 'Pratikno, Laborat'],
            ['3_RISTA_FISIO', 'Rista, Fisioterapi.'],
            ['3_RIZKISYAH', 'Rizkisyah Nastiti'],
            ['3_ROZIKIN', 'Rozikin'],
            ['3_SELVI_GIZI', 'Selvi, Gizi.'],
            ['3_SEPTIAN_YUDHA', 'Septian Yudha'],
            ['3_SUMARIYANTIK', 'Sumariyantik, Ass'],
            ['3_TEGUH_LAB', 'Teguh, Laborat'],
            ['3_UUN_GIZI', 'Uun, Gizi.'],
        ];

        DB::table('pelaksana')->upsert(
            array_map(fn (array $row) => [
                'no_proyek' => $row[0],
                'nama_pelaksana' => $row[1],
                'status_aktif' => true,
                'created_at' => $timestamp,
                'updated_at' => $timestamp,
            ], $data),
            ['no_proyek'],
            ['nama_pelaksana', 'updated_at'],
        );
    }
}
